const puppeteer = require('puppeteer');
const config = require('./config');

/**
 * Create branded HTML template with scraped report
 */
function createBrandedHTML(reportHTML, styles, userInfo) {
    const { fullName, email, position } = userInfo;
    const { logoUrl, companyName, primaryColor, secondaryColor, fontFamily } = config.branding;

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Audit Report - ${fullName}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        /* PDF Clean-up Styles */
        body {
            font-family: ${fontFamily};
            background: #ffffff !important;
            color: #1f2937;
            line-height: 1.6;
        }

        /* Hide only truly global site elements if necessary, but KEEP report-specific branding */
        .cookie-banner, .popup, .modal, .chat-widget, .side-cta-box-responsive,
        .w-nav-overlay, .toc-toggle-header, .ShareWidget_share-banner__MrfZJ, 
        .audit-side-cta-desktop, .BgDotImage_bg-dot-image__KDBCM {
            display: none !important;
        }

        /* Ensure Navbar and Footer from the site are visible */
        .NavbarForesight_navbar__E8mlO, .FooterUpdated_section__nVQhR, .FooterUpdated_footer__2pNXM {
            display: block !important;
            page-break-inside: avoid;
        }

        /* Layout Fidelity: Flow Ninja uses a flex layout for the main report */
        .report-layout {
            display: flex !important;
            flex-direction: row !important;
            gap: 40px;
        }

        .report-main-content {
            flex: 1;
        }

        .report-sidebar {
            width: 300px;
            display: block !important;
        }

        /* Score Hero Section Styling */
        .section.hero {
            background: #091030 !important;
            color: white !important;
            padding: 40px;
            border-radius: 16px;
            margin-bottom: 60px;
            display: flex !important;
            flex-direction: row !important;
            gap: 40px;
            align-items: center;
        }

        .report-score {
            font-size: 48px !important;
            font-weight: 700 !important;
            color: #4254FB !important;
        }

        /* Improvement Box Headers */
        .improvements-box {
            background: #fff;
            border: 1px solid #e5e7eb;
            padding: 30px;
            border-radius: 12px;
            margin-bottom: 30px;
            page-break-inside: avoid;
        }

        .improvements-box-header {
            display: flex !important;
            justify-content: space-between;
            align-items: center;
        }

        /* Rebranding specific overrides */
        [class*="NavbarForesight_brand"], [class*="FooterUpdated_footer-brand"] {
            /* If we need to swap the logo we could filter but user asked for name change */
        }
        
        .report-meta {
            margin: 20px 0;
            padding: 20px;
            background: #f9fafb;
            border-radius: 8px;
        }

        ${styles}
    </style>
</head>
<body>
    <div class="report-meta">
        <p><strong>Report Generated:</strong> ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    })}</p>
        <p><strong>Target URL:</strong> <a href="${userInfo.websiteUrl || '#'}">${userInfo.websiteUrl || 'N/A'}</a></p>
        <p><strong>Prepared for:</strong> ${fullName}, ${position}</p>
    </div>

    <div class="report-content">
        <!-- Content Injected Here - Scraped original site layout including rebrand -->
        ${reportHTML}
    </div>

    <div style="text-align: center; padding: 40px; color: #666; font-size: 12px;">
        <p>© ${new Date().getFullYear()} Sun Skill Techs. All rights reserved.</p>
        <p>Generated by Sun Skill Techs Team</p>
    </div>
</body>
</html>
    `.trim();
}

/**
 * Generate PDF from branded HTML
 */
async function generatePDF(reportHTML, styles, userInfo) {
    let browser = null;

    try {
        console.log('Generating PDF...');

        // Create branded HTML
        const brandedHTML = createBrandedHTML(reportHTML, styles, userInfo);

        // Launch browser for PDF generation
        browser = await puppeteer.launch({
            headless: 'new',
            protocolTimeout: 120000, // 120 seconds for large reports
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });

        const page = await browser.newPage();

        // Set content with increased timeout
        await page.setContent(brandedHTML, {
            waitUntil: 'networkidle0',
            timeout: 90000 // Increased to 90 seconds
        });

        // Wait for images and charts to load (with timeout protection)
        try {
            await page.evaluate(() => {
                return Promise.race([
                    Promise.all(
                        Array.from(document.images)
                            .filter(img => !img.complete)
                            .map(img => new Promise(resolve => {
                                img.onload = img.onerror = resolve;
                                // Timeout individual images after 5 seconds
                                setTimeout(resolve, 5000);
                            }))
                    ),
                    // Overall timeout after 30 seconds
                    new Promise(resolve => setTimeout(resolve, 30000))
                ]);
            });
        } catch (imageError) {
            console.log('Some images may not have loaded:', imageError.message);
        }

        // Additional wait for any dynamic content
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Generate PDF
        const pdfBuffer = await page.pdf({
            format: config.pdf.format,
            printBackground: config.pdf.printBackground,
            margin: config.pdf.margin,
            preferCSSPageSize: true
        });

        await browser.close();

        console.log('PDF generated successfully');

        return {
            success: true,
            pdfBuffer
        };

    } catch (error) {
        console.error('Error generating PDF:', error);

        if (browser) {
            await browser.close();
        }

        return {
            success: false,
            error: error.message
        };
    }
}

module.exports = {
    generatePDF,
    createBrandedHTML
};
